version: "3.9"  
services:
  node-maintenance:
    build: .
    command: ansible-playbook main.yaml -i inventory -l development
    # command: sleep infinity
    hostname: node_maintenance
    volumes:
      - ./:/opt/node-maintenance
      - ./development/ssh/keys/id_rsa:/root/.ssh/id_rsa